In [23]:
from scipy.spatial.distance import pdist, squareform
import numpy as np
import pandas 


def ExtractData (filename):

    features = []
    classes = []
    
    file = open(filename, 'r')

    for i in range(10):
        classes.append([i]*200)

    for line in file:
        row = line.split(';')
        features.append([float(x) for x in row ])

    mat_feat = np.matrix(features).astype(np.float)

    #matriz de dados
    return (mat_feat)

mat_fac = ExtractData('mfeat-fac.csv').astype(int)
mat_fou = ExtractData('mfeat-fou.csv')
#mat_kar = ExtractData('mfeat-kar.csv')

print('mat-fac:\n',mat_fac)
print('mat-fou:\n',mat_fou)
#print('mat-kar:\n',mat_kar)



mat-fac:
 [[ 98 236 531 ...  15  12  13]
 [121 193 607 ...  13  15  11]
 [115 141 590 ...  14  13   6]
 ...
 [337 299 852 ...  15  17  21]
 [247 261 866 ...  13  15  15]
 [355 379 867 ...  12  12  20]]
mat-fou:
 [[0.06588172 0.19731169 0.10382563 ... 0.39436572 0.04997072 0.34487096]
 [0.04914215 0.17597068 0.10551464 ... 0.44527711 0.08397801 0.35409193]
 [0.03417192 0.22764888 0.10876636 ... 0.44502912 0.07123367 0.2614646 ]
 ...
 [0.33560596 0.318426   0.25794822 ... 0.14157604 0.03877594 0.11459086]
 [0.25390962 0.17120241 0.30262199 ... 0.23032164 0.10366427 0.13000271]
 [0.27157485 0.14903681 0.23275253 ... 0.27576948 0.02107437 0.08524072]]


In [24]:
#calculo das matrizes de dissimilaridade
from scipy.spatial.distance import pdist, squareform


distancias_fac = pdist(mat_fac, metric='euclidean')
distancias_fou = pdist(mat_fou, metric='euclidean')
#distancias_kar = pdist(mat_kar, metric='euclidean')

mfeat_fac = squareform(distancias_fac)
mfeat_fou = squareform(distancias_fou)
#mfeat_kar = squareform(distancias_kar)

print(mfeat_fac)

[[   0.          566.27378537  633.99526812 ... 1535.42827902
  1447.88466391 1719.27659206]
 [ 566.27378537    0.          457.2089238  ... 1376.32481631
  1232.27594312 1586.15320824]
 [ 633.99526812  457.2089238     0.         ... 1396.93736438
  1255.33899804 1664.20130994]
 ...
 [1535.42827902 1376.32481631 1396.93736438 ...    0.
   546.94606681  633.03712371]
 [1447.88466391 1232.27594312 1255.33899804 ...  546.94606681
     0.          951.92751825]
 [1719.27659206 1586.15320824 1664.20130994 ...  633.03712371
   951.92751825    0.        ]]
