In [27]:
from scipy.spatial.distance import pdist, squareform
import numpy as np
import pandas 


def ExtractData (filename):

    features = []
    classes = []
    
    file = open(filename, 'r')

    for i in range(10):
        classes.append([i]*200)

    for line in file:
        row = line.split(';')
        features.append([float(x) for x in row ])

    mat_feat = np.matrix(features).astype(np.float)

    #matriz de dados
    return (mat_feat)

mat_fac = ExtractData('mfeat-fac.csv').astype(int)
mat_fou = ExtractData('mfeat-fou.csv')
mat_kar = ExtractData('mfeat-kar.csv')

print('mat-fac:\n',mat_fac)
print('mat-fou:\n',mat_fou)
print('mat-kar:\n',mat_kar)



mat-fac:
 [[ 98 236 531 ...  15  12  13]
 [121 193 607 ...  13  15  11]
 [115 141 590 ...  14  13   6]
 ...
 [337 299 852 ...  15  17  21]
 [247 261 866 ...  13  15  15]
 [355 379 867 ...  12  12  20]]
mat-fou:
 [[0.06588172 0.19731169 0.10382563 ... 0.39436572 0.04997072 0.34487096]
 [0.04914215 0.17597068 0.10551464 ... 0.44527711 0.08397801 0.35409193]
 [0.03417192 0.22764888 0.10876636 ... 0.44502912 0.07123367 0.2614646 ]
 ...
 [0.33560596 0.318426   0.25794822 ... 0.14157604 0.03877594 0.11459086]
 [0.25390962 0.17120241 0.30262199 ... 0.23032164 0.10366427 0.13000271]
 [0.27157485 0.14903681 0.23275253 ... 0.27576948 0.02107437 0.08524072]]
mat-kar:
 [[-1.02970076e+09 -1.16667890e+09  1.15606690e+09 ...  1.81469083e+08
  -1.35135269e+08 -4.73910360e-01]
 [-5.03600883e+08 -1.28853331e+09  1.61155220e-01 ...  4.85791740e-01
   6.42450570e-01  6.13107090e-01]
 [-9.63915730e+08 -6.65589762e+08  3.88686870e-01 ...  1.09774804e+08
   8.27182050e-01 -1.76784039e+08]
 ...
 [ 1.88161314e

In [30]:
#calculo das matrizes de dissimilaridade
from scipy.spatial.distance import pdist, squareform


distancias_fac = pdist(mat_fac, metric='euclidean')
distancias_fou = pdist(mat_fou, metric='euclidean')
distancias_kar = pdist(mat_kar, metric='euclidean')

mfeat_fac = squareform(distancias_fac)
mfeat_fou = squareform(distancias_fou)
mfeat_kar = squareform(distancias_kar)

print(mfeat_kar)

[[0.00000000e+00 1.90068575e+09 2.16201027e+09 ... 2.44829923e+09
  2.59396726e+09 3.05369949e+09]
 [1.90068575e+09 0.00000000e+00 1.84998619e+09 ... 2.09011423e+09
  1.93749102e+09 2.69105618e+09]
 [2.16201027e+09 1.84998619e+09 0.00000000e+00 ... 2.29580572e+09
  2.30378492e+09 3.06202824e+09]
 ...
 [2.44829923e+09 2.09011423e+09 2.29580572e+09 ... 0.00000000e+00
  1.56630840e+09 2.38143105e+09]
 [2.59396726e+09 1.93749102e+09 2.30378492e+09 ... 1.56630840e+09
  0.00000000e+00 2.51669747e+09]
 [3.05369949e+09 2.69105618e+09 3.06202824e+09 ... 2.38143105e+09
  2.51669747e+09 0.00000000e+00]]
